# syntax=docker/dockerfile:1

FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential libpq-dev libpq5 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements/base.txt requirements/dev.txt requirements/
RUN pip install --no-cache-dir -r requirements/dev.txt
EXPOSE 8000
ENTRYPOINT ["bash", "./start.dev.sh"]
